name: skori
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI.
  flutter_screenutil: ^5.7.0
  image_picker: ^0.8.7
  sliding_sheet: ^0.5.2
  cached_network_image: ^3.2.1
  country_calling_code_picker: ^2.0.1
  pin_code_fields: ^7.4.0
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.2.19
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  auto_size_text_pk:
  buttons_tabbar: ^1.3.6
  toggle_switch: ^2.1.0
  badges:
  modal_progress_hud_nsn: ^0.4.0
  flutter_widget_from_html: ^0.10.3
  url_launcher: ^6.1.11
  #flick_video_player: ^0.5.0
  csslib: 0.17.0
  video_player:
  chewie: ^1.7.4
  youtube_player_flutter: ^8.1.2
  dropdown_search: ^5.0.3






  # networks
  dio: ^5.3.3
  internet_connection_checker: ^0.0.1+4
  get_it: ^7.2.0



  #social
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  #  firebase_auth: ^4.14.1
  #  firebase_core: ^2.23.0


  # state management
  flutter_bloc: ^8.0.1

  #Utilities
  dartz: ^0.10.1
  rxdart: ^0.27.7
  keyboard_actions: ^4.1.0
  meta: ^1.7.0
  intl: ^0.17.0
  equatable: ^2.0.3
  email_validator: ^2.0.1
  uuid: ^3.0.6
  flutter_slidable: ^2.0.0
  permission_handler: ^10.2.0
  animated_bottom_navigation_bar: ^1.3.0
  auto_size_text: ^3.0.0
  get_storage:
  easy_localization: ^3.0.0
  lottie:
  flutter_launcher_icons:
  flutter_expanded_tile:
  flutter_share: ^2.0.0
  table_calendar:
  webview_flutter: ^4.2.4
  audio_session:
  percent_indicator: ^4.2.3



flutter_icons:

  image_path_android: "assets/images/ios_icon.png"
  image_path_ios: "assets/images/ios_icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  image: assets/images/logo.png
  background_image: assets/images/bg.png
  #  color: "#19204E"
  android_gravity: center
  ios: true


#  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/icon/
    - assets/lottie/



  fonts:
    - family: LsBlack
      fonts:
        - asset: assets/fonts/LamaSans-Black.ttf


    - family: LsExtraBold
      fonts:
        - asset: assets/fonts/LamaSans-ExtraBold.ttf


    - family: LsBold
      fonts:
        - asset: assets/fonts/LamaSans-Bold.ttf


    - family: LsMedium
      fonts:
        - asset: assets/fonts/LamaSans-Medium.ttf


    - family: LsRegular
      fonts:
        - asset: assets/fonts/LamaSans-Regular.ttf


    - family: LsSemiBold
      fonts:
        - asset: assets/fonts/LamaSans-SemiBold.ttf





