// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//             'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC6ABV4M_DvawLNA2rjtFYUr6EC2oW-xyM',
//     appId: '1:558011997608:android:4da889916871e5ccfed19d',
//     messagingSenderId: '558011997608',
//     projectId: 'imhere-92b8b',
//     storageBucket: 'imhere-92b8b.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBBS9-DJRm6UJ67M4M-q88QIuKJiIhoZn8',
//     appId: '1:558011997608:ios:5bbf4d7214ea4134fed19d',
//     messagingSenderId: '558011997608',
//     projectId: 'imhere-92b8b',
//     storageBucket: 'imhere-92b8b.appspot.com',
//     iosClientId: '558011997608-dr6n6c02a01t7lv4tidcj7b2is17i8ca.apps.googleusercontent.com',
//     iosBundleId: 'com.kian.imhere',
//   );
// }